### ISSUE TITLE
Bug in class YY_COMPRESSED_SCANNER_SKELETON

### ISSUE THREAD

**Issue by wjansen** [gobo-eiffel/gobo#12]
Just i've learned how to use send issues and pull requests to the GOBO list and immediately comes my first bug message. 

Class `YY_COMPRESSED_SCANNER_SKELETON` calls in line 191  procedure `KL_SPECIAL_ROUTINES.force` (there are more such calls). The feature name is a bit misleading since the routine does not resize the array if the capacity is exhausted. In class `YY_COMPRESSED_SCANNER_SKELETON` the a array is not resized either, so it may happen, depending on grammar and text, that a call to `force` will overwrite the data following the array in memory. And it does happen! 

Today, I had the case that the array in question (after calling `force`) had `count=6`, `capacity=3` for index =5. The type ident =137 of the object following the array was overwritten by 423, a not existing type number. The program soon crashed. 

After adding (in my own copy of GOBO) a resize statement before line 191 the crash disappeared and all things were fine, but I fear that there are many more dangerous calls of `force`. 

With regards 
Wolfgang

**Comment by ebezault** [comment]
Hi Wolfgang,

I was not able to see your fix (with the resize) in your fork of gobo in github.
I just had a quick look at the code in `YY_COMPRESSED_SCANNER_SKELETON` and apparently it was designed so that it didn't need any resize beyond the `capacity` which has been set in `yy_initialize` and `yy_set_content`. So I guess there is a flaw in the design. It would help if you could send me an example reproducing the problem.

**Comment by wjansen** [comment]
Twice sorry. First for missing the bug fix (I did not include it since I thought my solution is not the best). Here is it, add the following code before line 191 in class `YY_COMPRESSED_SCANNER_SKELETON`:
`	if yy_state_stack.capacity <= yy_state_count then`
`		yy_state_stack := yy_state_stack.aliased_resized_area (yy_state_count*2+1)`
`	end`
Multiplication by 2 to avoid most resizing operations when the stack constantly grows, addition of 1 to ensure that there is at least one free place if the stack had zero size. 

The second sorry concerns the example. I am not able to reproduce the bug. Yesterday it existed for some hours, after fixing it as described I made some more modifications in my own code (also in the heir class of `YY_COMPRESSED_SCANNER_SKELETON`, but the rules remained unchanged). The code where the bug appeared is not in the daily backup and cannot be restored easily. Any trial to recover the erroneous code failed: the bug disappeared even when `YY_COMPRESSED_SCANNER_SKELETON` is reset to its original state and, of course, the generated scanner is applied to the same text. A self-healing effect? 

--------------------------------------------------------------------------------------------------------------
BTW, here two more remarks on GELEX. 

I miss something like `no_token` as possible value of `last_token`. This concerns primarily the treatment of comments. For example, there are many code doublings in `ET_EIFFEL_SCANNER` like 
`[a-zA-Z][a-zA-Z0-9_]*   { ... }`
`[a-zA-Z][a-zA-Z0-9_]*/([ \t\r\n]|"--")  { ... }`
just to tackle line ends and comments. Rules like
`[ \t\r\n] { last_token := no_token }` 
`"--".*\n { last_token := no_token }` 
would allow to cancel all those code doublings. 
To be more precise. `no_token` denotes something that the scanner extracted as a token by its rules but that should be neglected by the parser (say, `read_token` continues working until `last_token` is set to another value, only this last value is reported to the parser). Within the scanner the `no_token` is used in some actions and these actions can do much more than merely setting `last_token := no_token`, e.g. a pretty-printer can do somewhat specific with comments. 
I found such a `no_token` in https://code.google.com/p/vala-lemon-extractor/ (there called `NO_ADD_TOKEN`), it simplified the rules essentially. 

Further, the vala-lemon-extractor provides an alternative for `set_start_condition`, namely a stack of start conditions treated by routines `push_state`, `pop_state`. A stack of start conditions makes things clearer than a simple value replacement. Can this be added to `YY_SCANNER`? For version compatibility, `set_start_condition` should be preserved, now with the new semantics of replacing the stack's top item. Syntax and semantics of existing code will not be broken.

**Comment by ebezault** [comment]
For the resizing problem in `YY_COMPRESSED_SCANNER_SKELETON`, the reason why I asked for an example to reproduce it is because I was wondering whether you were calling correctly the initialization routines which are supposed to make sure that the `capacity` is large enough.

For the suggestion to have something like:
`[ \t\r\n] { last_token := no_token }`
as a way for the parser to ignore these tokens, well, actually there is no need for such things. Providing no action:
`[ \t\r\n]`
or an action which does not set `last_token`:
`[ \t\r\n] { print ("Read a space") }`
already achieves this effect today.

For the way spaces and comments are handled in `ET_EIFFEL_SCANNER`, it's not duplication of code. This implementation has been done on purpose. The idea is that the AST factory can decide whether to attach the spaces and comments to the preceding token in the AST or not. Usually, the AST factory does not do that. So the code as it is in `ET_EIFFEL_SCANNER` looks like duplication of code. But in some cases (when using `ET_DECORATED_AST_FACTORY`) it is possible to keep the spaces and comments in the generated AST as they were in  the class text. This is useful when we want to write the AST back in a text form which looks exactly as it was in the original class text. For example, with this technique you can do some code coloring, or remove the `is` keyword without changing the indentation and keeping the comments, which are otherwise ignored when doing pure compilation. One way to achieve that without code duplication in the scanner file could have been to define this kind of token in the parser file:
`%token <ET_BREAK> T_BREAK`
and then write the following in the scanner file:
`[ \t\r\n] { create {ET_BREAK} last_break_value.make (text) ; last_token := T_BREAK}`
Then put `T_BREAK` everywhere in the grammar, and let the AST factory keep them or not when building the AST. But this technique pollutes the grammar, and it also means that even when the AST factory does not need to keep them, the scanner will create the `ET_BREAK` objects anyway. With the current implementation in `ET_EIFFEL_SCANNER`, the `ET_BREAK` objects are created by the AST factory, only when needed.

And finally, you suggestion to use a stack for start conditions is a good idea. I will implement it in gelex when I have time.

Thank you for your feedback.

**Comment by wjansen** [comment]
On 08/29/2015 10:27 AM, Eric Bezault wrote:
>
> For the resizing problem in |YY_COMPRESSED_SCANNER_SKELETON|, the 
> reason why I asked for an example to reproduce it is because I was 
> wondering whether you were calling correctly the initialization 
> routines which are supposed to make sure that the |capacity| is large 
> enough.
>
> For the suggestion to have something like:
> |[ \t\r\n] { last_token := no_token }|
> as a way for the parser to ignore these tokens, well, actually there 
> is no need for such things. Providing no action:
> |[ \t\r\n]|
> or an action which does not set |last_token|:
> |[ \t\r\n] { print ("Read a space") }|
> already achieves this effect today.
>
> For the way spaces and comments are handled in |ET_EIFFEL_SCANNER|, 
> it's not duplication of code. This implementation has been done on 
> purpose. The idea is that the AST factory can decide whether to attach 
> the spaces and comments to the preceding token in the AST or not. 
> Usually, the AST factory does not do that. So the code as it is in 
> |ET_EIFFEL_SCANNER| looks like duplication of code. But in some cases 
> (when using |ET_DECORATED_AST_FACTORY|) it is possible to keep the 
> spaces and comments in the generated AST as they were in the class 
> text. This is useful when we want to write the AST back in a text form 
> which looks exactly as it was in the original class text. For example, 
> with this technique you can do some code coloring, or remove the |is| 
> keyword without changing the indentation and keeping the comments, 
> which are otherwise ignored when doing pure compilation. One way to 
> achieve that without code duplication in the scanne! r file co uld 
> have been to define this kind of token in the parser file:
> |%token <ET_BREAK> T_BREAK|
> and then write the following in the scanner file:
> |[ \t\r\n] { create {ET_BREAK} last_break_value.make (text) ; 
> last_token := T_BREAK}|
> Then put |T_BREAK| everywhere in the grammar, and let the AST factory 
> keep them or not when building the AST. But this technique pollutes 
> the grammar, and it also means that even when the AST factory does not 
> need to keep them, the scanner will create the |ET_BREAK| objects 
> anyway. With the current implementation in |ET_EIFFEL_SCANNER|, the 
> |ET_BREAK| objects are created by the AST factory, only when needed.
>
> And finally, you suggestion to use a stack for start conditions is a 
> good idea. I will implement it in gelex when I have time.
>
> Thank you for your feedback.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gobo-eiffel/gobo/issues/12#issuecomment-135961308>.
>

I see, it was my mistake to assume that the default value of 
`last_token` is 0 meaning EOF.
And now I understand the reason of the code doublings. Here (i.e. for 
use of pretty-printing source code within the debugger) I may drop 
without trouble what I called code doublings.

Meanwhile, I have constructed a crashing example scanner. In fact, 
initialization is not standard. The scanner should be able not only to 
scan whole files but also selected line ranges. So, we skip over leading 
lines, then read the text line-by-line and feed these lines into the 
scanner until all interesting lines have been treated. The scanner is 
always the same, it is reset before the next line is fed in. Maybe that 
the reset operation is not complete.
In my working program I changed the strategy from reading line-by-line 
to reading all the rest of the file (after skipping the first part) and 
terminating the scan by the `pre_action` when the actual line number 
exceeds the needed line count. Anyway, also here I cannot reuse the 
scanner for multiple files (or line ranges): after reset the scanner 
produces confusion only.

The attachment contains a small example scanner that implements the 
first approach. For simplicity, the scanner rules are those of the GELEX 
example.
Installation:
   gelex -o scanner.e scanner.l
   gec test.xace
Run:
   scan exa.e
   scan test.e
On my computer the first example ("exa.e") is fine while the second 
("test.e") does crash. Which example will crash may depend on the 
platform, i.e. on the way C compiler and memory allocator distribute 
objects on memory.

-- 
Dr. Wolfgang Jansen
Lauenburger Straße 40
D-12169 Berlin

Tel: (+49) 0172 40 86 916
e-mail: wo.jansen@kabelmail.de


%{
indexing

    description: "Scanner for a toy Eiffel-like language"

class SCANNER

inherit

	YY_COMPRESSED_SCANNER_SKELETON
		export 
			{NONE} scan	-- only use `scan_lines'
		redefine
			make
		end
	
create

    make
%}

DIGIT    [0-9]
ID       [A-Za-z][A-Za-z0-9_]*

%%

{DIGIT}+    {
                 io.put_string ("An integer: ")
                 io.put_integer (text.to_integer)
                 io.put_new_line
            }
{DIGIT}+"."{DIGIT}*  {
                 io.put_string ("A real: ")
                 io.put_real (text.to_real)
                 io.put_new_line
            }
class|inherit|feature|is|do|if|then|else|end    {
                 io.put_string ("A keyword: ")
                 io.put_string (text)
                 io.put_new_line
            }
{ID}        {
                 io.put_string ("An identifier: ")
                 io.put_string (text)
                 io.put_new_line
            }
"+"|"-"|"*"|"/"|"^"    {
                 io.put_string ("An operator: ")
                 io.put_character (text_item (1))
                 io.put_new_line
            }
"--".*           -- Ignore comments
[ \t\n\r]+       -- Ignore separators
.           {
                 io.put_string ("Unrecognized character: ")
                 io.put_character (text_item (1))
                 io.put_new_line
            }

%%

feature {NONE} -- Initialization

	make
		do
			make_with_buffer (new_string_buffer (""))
		end

feature -- Access

	lines_scanned: INTEGER
	
feature -- Scanning

	scan_lines (fn: STRING; first, last: INTEGER)
		local
			f: KL_TEXT_INPUT_FILE
			i: INTEGER
		do
			i := first.max (1)
			if last >= i then
				create f.make (fn)
				f.open_read 
				if f.exists and then f.is_open_read then
					from
					until i >= first or else f.end_of_file loop
						f.read_line
						i := i + 1
					end
					from
						f.read_line
					until i > last or else f.end_of_file loop
						reset
						input_buffer.wipe_out	-- necessary after `reset'?
						input_buffer.content.fill_from_string (f.last_string, 1)
						scan
						i := i + 1
						lines_scanned := lines_scanned + 1
						f.read_line
					end
					f.close
				end
			end
		end

end

**Comment by ebezault** [comment]
Hi Wolfgang,

I did try to run your example, but just looking at the code I can see where the initialization has been by-passed. You should replace the two lines:

`input_buffer.wipe_out
input_buffer.content.fill_from_string (f.last_string, 1)`

by:

`set_input_buffer (new_string_buffer (f.last_string))`

Otherwise, you modified the buffer but the scanner does not know about this change. It's like changing the value of the hash-code of a key after you inserted it in a hash-table. If the hash-table does not know about this change, then it will end up in a corrupted state. It's the same thing here: the scanner has been initialized with the old content of the input buffer. It does not know that you modified it. So what has been initialized is not in sync with what is currently in the buffer.

**Comment by wjansen** [comment]
Your proposal is what I had as a workaround in my project program. I was 
not happy with it: the intension was to reuse the scanner including the 
reuse of its by far largest component `input_buffer.content`. I do not 
understand your comparison with hash-tables. The data of interest 
`{YY_SCANNER}.input_buffer.content` is accessible from within the class, 
one has to use the data and, if necessary, to modify it (or the code 
around). After doing a bit code mining, I was able to add code such that 
`input_buffer.content` may be reused. The attachment "yy.zip" contains 
the modified source code.
In detail, routines `reset_for_file`, `reset_for_string` in `YY_SCANNER` 
forward the task to routines `reset_for_file`, `reset_for_string` in 
classes `YY_FILE_BUFFER`, `YY_BUFFER`, resp., the latter routines do the 
job. Attachment "scan.zip" is the updated example that calls 
`reset_for_string` for each input line. The example does not longer 
crash (even for very long input files). And my project program (with 
`reset_for_file`) works very well with the updated scanner.

Being on the way, I implemented also the stack of start conditions. 
Surprisingly, such an implementation existed already in class 
`XM_EIFFEL_SCANNER_SKELETON`. I moved the corresponding code (with minor 
variations) to `YY_SCANNER`. Moreover, class `LX_LEX_PARSER_SKELETON` 
has its own `push_start_condition` with a different semantics. There I 
renamed the from "YY_SCANNER" inherited routine away. All this is 
contained in "yy.zip".

-- 
Dr. Wolfgang Jansenreset_for_file
Lauenburger Straße 40
D-12169 Berlin

Tel: (+49) 0172 40 86 916
e-mail: wo.jansen@kabelmail.de

**Comment by ebezault** [comment]
It's not clear to me where I can get the attachments in this page. I don't see them.

You didn't understand the analogy with hash-table. Well, the hash code of the keys is also available from within the hash-table, just like `input_buffer.content` for the scanner. In case of hash-table, we could imagine having a routine in hash table which when called would recompute the position of each key based on their new hash-code value. So, some client changing the value of the hash code of a key in a hash table would have to call this routine for the hash-table to be usable again. This is more optimal in terms of performance than letting the hash-table figure out by itself, at each operations performed on it, whether some hash code has changed.

Likewise for the scanner. Of course it's possible to reuse the memory use by the buffer. But like with the hash-table, we have to let the scanner know that its content has changed. Letting the scanner figure that out by itself each time it needs to read from the buffer is not optimal in terms of performance. So, having a routine which modifies the buffer and updates the internals of the scanner accordingly is OK. Looking at `set_input_buffer` may help figuring out what internals need to be updated when modifying the buffer.

**Comment by wjansen** [comment]
The plan was not to build an observer of the buffer contents. The plan 
was merely to be able to reuse the buffer (and its voluminous `content` 
field) when the client class starts a new scan. It is the client's 
responsibility to tell the scanner that new data is to be scanned from 
scratch,
the scanner's responsibility is then to reset its resources (but not to 
create new ones if ever possible). If between those reset requests 
another call to the scanner (say by `set_input_buffer`) forced the 
scanner to use a new buffer then this is mainly bad design of the client 
side. In such a case the next reset request simply forces the reuse of 
this other buffer, that's all. Anyway, the scanner _knows_ that the 
buffer content changed since the new buffer content has been set by the 
scanner itself (on client request).

So, what I have done is to add `reset...` routines to the scanner that 
let reuse (and refill!) its resources when requested and, on the client 
side (i.e. the example), to call these routines before any new scan. The 
additional code was necessary because the existing `reset` routine 
resets the scanner's internal state but not the buffer. New data was 
expected to be provided by providing a new buffer. And it had to be a 
new buffer since filling of a buffer was only possible by the buffer's 
creation routines. (My first trial to bypass this overhead failed and 
initiated the current discussion.) The new `reset...` routines allow the 
client to feed new data directly into the scanner, the intermediary step 
of creating and filling a buffer is avoided (well, a buffer is filled 
namely the existing one, but this is no longer the client's job).

PS:
I resent the attachments, now to ericb@gobosoft.com. I hope this works.

-- 
Dr. Wolfgang Jansen
Lauenburger Straße 40
D-12169 Berlin

Tel: (+49) 0172 40 86 916
e-mail: wo.jansen@kabelmail.de

**Comment by ebezault** [comment]
Implemented in commit#e730ac79ab0f4f488e02e454ac719301878b688a.
