### ISSUE TITLE
Create a develop branch

### ISSUE THREAD

**Issue by gchauvet** [gobo-eiffel/gobo#17]
When we push requests on GOBO tools, we need to update C source code generated. This is a huge diff process for Git.

It will be interesting to update the C source code bootstrap on master branch when all development commits are validated ?

**Comment by ebezault** [comment]
Personally I regenerate the C code in the bootstrap folder only when I introduce a modification which is not backward compatible. If the tools compiled from the C code in the bootstrap folder are still able to process the code in the Git repo at least during the first phase of the bootstrap process, then I leave them as they are. As you figured out, committing these C files fills in the Git repo rapidly, so I avoid doing that when it's not necessary (i.e. when the bootstrap process still work correctly).

**Comment by gchauvet** [comment]
An idea to avoid a over-consumption for C source code bootstrap files :
Use a zip archive (2,9 Mb vs 30 Mb raw C source files).

**Comment by ebezault** [comment]
Note that Git already compresses the files in the .git folder.

**Comment by gchauvet** [comment]
I'm agree, but pulling a 3Mb binary archive may be less greedy than a full 30Mb diff patch.
However, GIT have some issues to manage (very) large binary data. The general recommendation is to not have git repositories larger than 1GB to preserve performance.

**Comment by ebezault** [comment]
So the solution is the one I suggested earlier: update the bootstrap C files only when a backward-incompatible modification which prevents the bootstrap from working has been introduced. I work very often on `gec`, but I don't have to regenerate the bootstrap C files that often (because the compiler generated from these C files is still able to compile the new Eiffel code).

**Comment by gchauvet** [comment]
Ok, this request is not usefull
