### ISSUE TITLE
Implicit variable pointer generate unvalid C code

### ISSUE THREAD

**Issue by gchauvet** [gobo-eiffel/gobo#19]
Please find attached a snippet  when I try to send a C pointer of an Eiffel string without using an intermediate variable pointer :
```eiffel
compile_string (content: STRING)
                require
                        a_not_empty_content: not content.is_empty
                local
                        l_exception: WR_TCC_EXCEPTION
                        l_code: INTEGER
                        l_value: ANY
                do
                        l_value := content.to_c
                        l_code := tcc_compile_string (context, $(content.to_c)) -- << Bug without Eiffel error/warning
                        -- l_code := tcc_compile_string (context, $l_value)
                        if l_code < 0 then
                                create l_exception.make (l_code)
                                l_exception.raise
                        end
        end

```

My favourite C compiler returns me :
```
error: request for member ‘a1’ in something not a structure or union
  t1 = ((0).a1);
```

**Comment by ebezault** [comment]
I can confirm that this is a bug. See `ET_C_GENERATOR.print_expression_address`.
However, please note that as far as I know, this Eiffel construct is not part of the ECMA Eiffel standard. So you are better off using your workaround with `l_value`.

I also want to raise your attention to the fact the exceptions as objects are not supported  by `gec`. See `$GOBO/library/free_elks/fale/exception.e`. If this is a problem for you, I could at least implement `EXCEPTION.raise` using `EXCEPTIONS.raise`.

**Comment by gchauvet** [comment]
I browsed ECMA-367, section 8.28.1 (book page 137):
```
Address: "$" Variable
```
"Variable" cannot be a method call or a parenthesized expression. The construction below
```eiffel
l_code := tcc_compile_string (context, $content.to_c)
```
Raise a syntax error as expected.

Concerning implementation of exceptions as objects, I will be happy to have this mechanism. However I don't know how many effort this feature required to be implemented. If time consuming is too high for you, I can wait.

**Comment by ebezault** [comment]
The version with the parentheses:
```
$(content.to_c)
```
is still accepted for backward compatibility. It was valid in the old days.

For exceptions, having a full implementation of exceptions as objects requires indeed some effort. But making sure that `EXCEPTION.raise` raises at least a non-object exception (which can then be caught in a `rescue` clause) is easy. As I said before, I just have to make sure that `EXCEPTION.raise` calls `EXCEPTIONS.raise`.

**Comment by ebezault** [comment]
Both bugs:
* Invalid C code generated for $(expression)
* EXCEPTION.raise not raising an exception

have been fixed. Exceptions as objects are still not supported by `gec` though.
