### ISSUE TITLE
Cannot bootstrap in Linux

### ISSUE THREAD

**Issue by schoelle** [gobo-eiffel/gobo#23]
Hi,
I just cloned the current master and get errors which I try to bootstrap:

<code>
/home/schoelle/Code/gobo/work/bootstrap/gec18.c:27355:8: warning: return type defaults to ‘int’ [-Wimplicit-int]
 static GE_init_exception_trace_buffer(GE_exception_trace_buffer* a_trace)
        ^
/home/schoelle/Code/gobo/work/bootstrap/gec18.c:27369:8: warning: return type defaults to ‘int’ [-Wimplicit-int]
 static GE_append_to_exception_trace_buffer(GE_exception_trace_buffer* a_trace, char* a_string)
        ^
/home/schoelle/Code/gobo/work/bootstrap/gec18.c:27396:8: warning: return type defaults to ‘int’ [-Wimplicit-int]
 static GE_wipe_out_exception_trace_buffer(GE_exception_trace_buffer* a_trace)
        ^
/home/schoelle/Code/gobo/work/bootstrap/gec18.c: In function ‘GE_jump_to_last_rescue’:
/home/schoelle/Code/gobo/work/bootstrap/gec18.c:27731:4: warning: format not a string literal and no format arguments [-Wformat-security]
    fprintf(stderr, l_exception_trace);
    ^
/home/schoelle/Code/gobo/work/bootstrap/gec18.c: In function ‘GE_raise_exception’:
/home/schoelle/Code/gobo/work/bootstrap/gec18.c:27825:4: warning: format not a string literal and no format arguments [-Wformat-security]
    fprintf(stderr, l_trace);
    ^
/home/schoelle/Code/gobo/work/bootstrap/gec18.c: At top level:
/home/schoelle/Code/gobo/work/bootstrap/gec18.c:31629:22: fatal error: winerror.h: No such file or directory
compilation terminated.
</code>

I went back to 5560840 and bootstrapping works fine. Looks like the current checked in C code will not compile on GCC.

**Comment by ebezault** [comment]
Thank you for reporting this issue.
Please try again.

**Comment by schoelle** [comment]
Looks much better now, but I do get strange error messages concerning #endif; - the semicolon looks wrong.

**Comment by ebezault** [comment]
It should be fixed now.
But I made many more modifications, so I hope that I didn't break anything else.

**Comment by schoelle** [comment]
Tons of error again, these are probably the important ones:

```
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92185:29: note: (near initialization for ‘GE_type_infos[669].new_instance’)
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92186:10: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 {670, 0, &GE_new670, 0},
          ^
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92186:10: note: (near initialization for ‘GE_type_infos[670].new_instance’)
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92189:29: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 {673, GE_TYPE_FLAG_SPECIAL, &GE_new673, 0},
                             ^
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92189:29: note: (near initialization for ‘GE_type_infos[673].new_instance’)
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92190:29: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 {674, GE_TYPE_FLAG_SPECIAL, &GE_new674, 0}
                             ^
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92190:29: note: (near initialization for ‘GE_type_infos[674].new_instance’)
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92349:8: warning: return type defaults to ‘int’ [-Wimplicit-int]
 static GE_init_exception_trace_buffer(GE_exception_trace_buffer* a_trace)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92363:8: warning: return type defaults to ‘int’ [-Wimplicit-int]
 static GE_append_to_exception_trace_buffer(GE_exception_trace_buffer* a_trace, char* a_string)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:92390:8: warning: return type defaults to ‘int’ [-Wimplicit-int]
 static GE_wipe_out_exception_trace_buffer(GE_exception_trace_buffer* a_trace)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/schoelle/Code/gobo/work/bootstrap/geant2.c:97098:22: fatal error: winerror.h: No such file or directory
 #include <winerror.h>
                      ^
compilation terminated.
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
geant1.o: In function `GE_boxed1':
geant1.c:(.text+0x1b): undefined reference to `GE_check_null'
geant1.o: In function `GE_boxed2':
geant1.c:(.text+0x58): undefined reference to `GE_check_null'
geant1.o: In function `GE_boxed3':
geant1.c:(.text+0x93): undefined reference to `GE_check_null'
geant1.o: In function `GE_boxed4':
geant1.c:(.text+0xcf): undefined reference to `GE_check_null'
geant1.o: In function `GE_boxed5':
geant1.c:(.text+0x10d): undefined reference to `GE_check_null'
geant1.o:geant1.c:(.text+0x149): more undefined references to `GE_check_null' follow
geant1.o: In function `T20x27T0':
geant1.c:(.text+0x691): undefined reference to `GE_check_void'
geant1.c:(.text+0x6c3): undefined reference to `GE_check_void'
geant1.c:(.text+0x6f8): undefined reference to `GE_check_void'
geant1.c:(.text+0x71d): undefined reference to `GE_check_void'
geant1.c:(.text+0x742): undefined reference to `GE_check_void'
geant1.o: In function `T36x2517T0':
geant1.c:(.text+0x798): undefined reference to `T32f49'
geant1.c:(.text+0x7b1): undefined reference to `T36f32'

```

**Comment by ebezault** [comment]
:-( 
I hope it will be better now.

**Comment by ebezault** [comment]
Did you get a chance to give it another try?
Thanks.

**Comment by schoelle** [comment]
Sorry for the slow feedback: all working, thanks!
