### ISSUE TITLE
Which norm of regexp is follow this library?

### ISSUE THREAD

**Issue by phgachoud** [gobo-eiffel/gobo#38]
Hi,

Which regexp norm is RX_PCRE_REGULAR_EXPRESSION following?

As there are [many implementations](https://stackoverflow.com/questions/8639519/differences-between-regex-types) of regexp, I'm looking for a reference for this lib.

sorry if you mentioned it and I didn't find it, the first place I'd look for is on the RX_PCRE_REGULAR_EXPRESSION class comment.

**Comment by ebezault** [comment]
I'm not sure what you mean by regex norm. I'm not the original author of this library, but from the name I think that it supports the flavor as implemented in PCRE (or at least a subset of it at the time this Eiffel library was developed). Does that answer your question?

Note that I'm currently working on this library to make it support Unicode (using `STRING_32` directly, not UTF-8 as intermediary format). But this work has not been released yet.

**Comment by phgachoud** [comment]
Precised my question. I'm looking for a regexp format reference for this lib. Thx for your answer!

**Comment by ebezault** [comment]
Yes, or as I mentioned above, a subset of it as it was at the time this Eiffel library was developed.
