### ISSUE TITLE
Mailing list address

### ISSUE THREAD

**Issue by kwaxer** [gobo-eiffel/gobo#50]
The README references Yahoo Groups as a mailing list for the project. But they were terminated some time ago (no idea if there are any archives). It would be great to update the README with the links that still work, e.g. to Sourceforge, or remove the mention of user lists altogether.

**Comment by ebezault** [comment]
Fixed in https://github.com/gobo-eiffel/gobo/commit/a1923adc736d9dfce6630c3454a62412c4778932
