### ISSUE TITLE
Q: how to print eiffel object size in bytes

### ISSUE THREAD

**Issue by mw66** [gobo-eiffel/gobo#65]
Hi,

Is there a way to print eiffel object size in bytes?

Better to be a cross compliers solution.

Thanks

**Comment by ebezault** [comment]
Did you try [INTERNAL.physical_size_64](https://github.com/gobo-eiffel/gobo/blob/master/library/free_elks/src/elks/support/internal.e#L707)?

**Comment by mw66** [comment]
Thanks.
