### ISSUE TITLE
How to set the make jobs used by `geant`?

### ISSUE THREAD

**Issue by ghost** [gobo-eiffel/gobo#67]
GNU Make and Ninja both has the `-j` switch to specify the make jobs to be used. I can't find anything equivalent for `geant`. It seems it will always set the make jobs equals to the number of CPU cores. I think the make jobs should be customizable. I'm building on a VPS where there are 4 cores but only 4GB of RAM. I always got OOM with GCC (and this always happened at the building of `gexslt`).

**Comment by ebezault** [comment]
There is now a new command-line option `--thread` for `geant`.
Also, the default is now to use 3 less CPU cores than available (with a minimum of 1 of course).
