### ISSUE TITLE
[GEANT] Allow relative parent location

### ISSUE THREAD

**Issue by gchauvet** [gobo-eiffel/gobo#9]
I try to load a parent configuration file relative to the same current configuration folder, without success:

Please find attached a diff patch that reproduce the issue.
To test it, launch the bootstrap process.
```
--- a/misc/eiffel.eant
+++ b/misc/eiffel.eant
@@ -11,7 +11,7 @@
        </description>
 
        <inherit>
-               <parent location="${GOBO}/misc/ge2e.eant"/>
+               <parent location="ge2e.eant"/>
        </inherit>
```

**Comment by ebezault** [comment]
See pull request #10. Let me know if it works for you.
There might be other cases in geant where relative pathnames are not taken from the directory of the enclosing eant file.  I only looked at the issue reported here.

**Comment by gchauvet** [comment]
Your pull request #10 works for me.

**Comment by ebezault** [comment]
Merged.
